### 魔法命令
#### %run 运行指定路径下的python文件
#### %timeit 测试时间
#### %%timeit 区域命令符
#### %lsmagic 查看其他魔法命令

## numpy.array基础

In [1]:
import numpy

In [2]:
numpy.__version__

'1.15.4'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.15.4'

### Python List的特点

In [5]:
L  = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
import array
arr = array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array模块的array()函数的第一个参数为数组元素的类型，第二个参数为数组元素，如果使用array模块的array()函数来生成数组，那么就不能和列表一样使不同类型的值放置在同一个列表中

array模块的array()函数生成的数组没有把生成的对象当成一个向量或者矩阵，所以不支持线性代数里面的运算

下面这个例子是始图把用array生成的数组更改其中元素为不同的元素

In [7]:
arr[2] = 'hello'

TypeError: an integer is required (got type str)

### 使用numpy.array创建数组（矩阵）

In [9]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
nparr[5] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [11]:
nparr.dtype

dtype('int32')

### 其他创建numpy.array的方法

#### np.zeros()

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10,dtype =float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((3,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### np.ones()

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### np.full()

In [22]:
np.full(10,6)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [23]:
np.full((3,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [24]:
np.full(fill_value=666,shape=(3,5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

#### np.arange()

In [25]:
#python列表
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [26]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
#python列表步长为小数
[i for i in range(0,1,0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [29]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### np.linspace()

定义起点和终点，等间距的划分出需要的数据个数(包含头尾)

In [34]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [35]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [36]:
np.linspace(0,1,19)

array([0.        , 0.05555556, 0.11111111, 0.16666667, 0.22222222,
       0.27777778, 0.33333333, 0.38888889, 0.44444444, 0.5       ,
       0.55555556, 0.61111111, 0.66666667, 0.72222222, 0.77777778,
       0.83333333, 0.88888889, 0.94444444, 1.        ])

In [37]:
np.linspace(0,1,18)

array([0.        , 0.05882353, 0.11764706, 0.17647059, 0.23529412,
       0.29411765, 0.35294118, 0.41176471, 0.47058824, 0.52941176,
       0.58823529, 0.64705882, 0.70588235, 0.76470588, 0.82352941,
       0.88235294, 0.94117647, 1.        ])

In [38]:
np.linspace(0,1,21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

#### np.random
##### np.random.randint()

In [39]:
np.random.randint(10)

3

In [40]:
np.random.randint(10)

0

In [41]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.random.randint(0,10,size= 10)

array([8, 8, 2, 6, 4, 2, 0, 0, 3, 4])

In [43]:
np.random.randint(0,10,size= (3,5))

array([[9, 0, 8, 2, 9],
       [8, 0, 1, 2, 9],
       [5, 3, 7, 4, 3]])

#### np.random.seed()

设置随机数种子，保持随机数生成一致

如果想要生成的随机数一致，那就要在生成前设置一致的seed()

In [44]:
np.random.seed(666)

In [45]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [46]:
np.random.randint(0, 10, size=(3, 5))

array([[4, 4, 0, 0, 4],
       [0, 4, 5, 7, 1],
       [0, 0, 6, 6, 0]])

In [47]:
np.random.seed(666)

In [48]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

#### np.random.random()

In [49]:
np.random.random()

0.7315955468480113

In [50]:
np.random.random((3,5))

array([[0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197],
       [0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896],
       [0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259]])

#### np.random.normal()

In [51]:
np.random.normal()

0.9047266176428719

In [52]:
np.random.normal()

-0.8262832650185377

In [53]:
np.random.normal(10,100)

92.10136919707703

In [54]:
np.random.normal(0, 1, (3, 5))

array([[ 0.36712592,  1.65399586,  0.13946473, -1.21715355, -0.99494737],
       [-1.56448586, -1.62879004,  1.23174866, -0.91360034, -0.27084407],
       [ 1.42024914, -0.98226439,  0.80976498,  1.85205227,  1.67819021]])

In [58]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

### numpy.array的基本操作

In [60]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
x.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### numpy.array的属性

In [62]:
x.ndim

1

In [63]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
x.shape

(10,)

In [65]:
x.size

10

In [67]:
X = np.arange(20).reshape(4,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
x[5]

5

In [69]:
#不建议使用以下方法访问多维数组的元素
X[0][0]

0

In [70]:
#建议用这种方式
X[0,4]

4

In [71]:
X[0,-2]

3

In [72]:
x[:5]

array([0, 1, 2, 3, 4])

In [73]:
x[::2]

array([0, 2, 4, 6, 8])

In [74]:
x[1::2]

array([1, 3, 5, 7, 9])

In [75]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [76]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [77]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
X[:2][:1]
#相当于两次的在行方向上进行取

array([[0, 1, 2, 3, 4]])

在np.array的数组赋值给另一个变量时，是类似于索引的方式传递的，所以改变背赋值的数组变量也会改变原数组

不论是切片的形式还是完全赋值的形式

In [80]:
subX = X[:2,:3]

In [81]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [82]:
subX[1,1] = 1524
subX

array([[   0,    1,    2],
       [   5, 1524,    7]])

In [83]:
X

array([[   0,    1,    2,    3,    4],
       [   5, 1524,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19]])

In [84]:
x.shape

(10,)

In [85]:
x.ndim

1

In [86]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
A = x.reshape(2,5)

In [89]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
A.ndim

2

In [91]:
A[1,4] = 1566
x

array([   0,    1,    2,    3,    4,    5,    6,    7,    8, 1566])

In [92]:
A.shape

(2, 5)

In [93]:
B = x.reshape(1,10)

In [94]:
B

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8, 1566]])

In [95]:
B.ndim

2

In [96]:
B.shape

(1, 10)

在使用reshape时，对仍和维度参数定义为-1的意思就是让numpy自己运算后得到该维度的元素个数，保持最终的总元素个数不变

In [98]:
#只给出第二维的元素个数
x.reshape(-1,5)

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7,    8, 1566]])

In [99]:
#只给出第一维的元素个数
x.reshape(10,-1)

array([[   0],
       [   1],
       [   2],
       [   3],
       [   4],
       [   5],
       [   6],
       [   7],
       [   8],
       [1566]])

### numpy.array的合并和分割

In [100]:
m = np.array([1,2,3])
n = np.array([1,5,6])

In [102]:
#横向拼接，对于多维也适用
np.concatenate([m,n])

array([1, 2, 3, 1, 5, 6])

In [103]:
np.concatenate([n,m])

array([1, 5, 6, 1, 2, 3])

In [107]:
nn = np.array([1,2,3,4,5,6])
mm = np.array([1,45,8,64,65,67])

In [108]:
np.concatenate([nn.reshape(3,-1),mm.reshape(3,-1)])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1, 45],
       [ 8, 64],
       [65, 67]])

In [109]:
np.concatenate([nn.reshape(3,-1),mm.reshape(3,-1)]).shape

(6, 2)

In [110]:
z = np.array([666, 666, 666])

In [111]:
z.shape

(3,)

In [112]:
z.reshape(1,-1).shape

(1, 3)

In [113]:
z = z.reshape(1,-1)

In [114]:
nm = nn.reshape(2,-1)

In [115]:
np.concatenate(z,nm)
#不知为何失败

TypeError: only integer scalar arrays can be converted to a scalar index

In [116]:
z

array([[666, 666, 666]])

In [117]:
nm

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
z.dtype

dtype('int32')

In [119]:
nm.dtype

dtype('int32')

In [120]:
np.concatenate(z,nm,axis = 1)

TypeError: Argument given by name ('axis') and position (2)

In [126]:
np.concatenate(nm,z)

TypeError: only integer scalar arrays can be converted to a scalar index

In [127]:
np.concatenate([nm,z])
#注意添加括号[]

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [128]:
np.concatenate([nm,z],axis = 1)
##表面axis = 1 时是第二个维度，也就是最里面[]的元素个数

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [129]:
#验证一下
nm.shape

(2, 3)

In [130]:
z.shape

(1, 3)

In [131]:
np.concatenate([nm,nm])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [132]:
np.concatenate([nm,nm],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [133]:
np.vstack([z,nm]) # 等于 np.concatenate([nm,nm])

array([[666, 666, 666],
       [  1,   2,   3],
       [  4,   5,   6]])

### numpy.array的分割

In [135]:
s = np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
s1,s2,s3 = np.array_split(s,[3,7])

In [137]:
s1

array([0, 1, 2])

In [138]:
s2

array([3, 4, 5, 6])

In [139]:
s3

array([7, 8, 9])

In [141]:
s1,s2,s3 = np.hsplit(s,[2,8])

In [142]:
s1

array([0, 1])

In [143]:
s2

array([2, 3, 4, 5, 6, 7])

In [144]:
s3

array([8, 9])

In [145]:
s1,s2,s3 = np.split(s,[1,9])

In [146]:
s1

array([0])

In [147]:
s2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
s3

array([9])

In [149]:
ss = np.arange(25).reshape(5,5)
ss

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [150]:
ss1,ss2 = np.split(ss,[2])

In [151]:
ss1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [152]:
ss2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [153]:
ss1,ss2 = np.split(ss,[2],axis=1)

In [154]:
ss1

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [155]:
ss2

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [156]:
ss1,ss2 = np.vsplit(ss,[2])

In [157]:
ss1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [158]:
ss2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [159]:
ss1,ss2 = np.hsplit(ss,[2])

In [160]:
ss1

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [161]:
ss2

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

### numpy.array中的运算

In [162]:
L = [i for i in range(10)]

In [163]:
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [166]:
%%time
A = []
for e in L:
    A.append(2*e)

Wall time: 0 ns


In [167]:
L = [i for i in range(10000000)]

In [168]:
%%time
A = []
for e in L:
    A.append(2*e)

Wall time: 2.89 s


In [170]:
%%time
A = [2*e for e in L]

Wall time: 1.81 s


In [171]:
%%time
A = np.array(2*e for e in L)

Wall time: 294 ms


In [172]:
%%time
A = 2*L

Wall time: 347 ms
